services:
  backend:
    build: ./backend
    container_name: techgigs-crm-backend
    restart: always
    ports:
      - "4400:5000"        
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: techgigs-crm-frontend
    restart: always
    ports:
      - "3300:80"          
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: techgigs-crm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3564744n
      POSTGRES_DB: techgigs_crm
    volumes:
      - techgigs_crm_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"      

volumes:
  techgigs_crm_data: